import { existsSync, readFileSync } from 'node:fs'
import {
  defineNuxtModule,
  addComponentsDir,
  createResolver,
  addTemplate,
  updateTemplates,
  useLogger,
  addTypeTemplate,
} from '@nuxt/kit'
import { resolve } from 'pathe'
import { parse } from '@vue/compiler-sfc'
import { defu } from 'defu'
import { extractStoryContent } from './utils/template-extraction'

interface StoryComponent {
  pascalName: string
  kebabName: string
  shortPath: string
  global?: boolean | string
  srcDir: string
  template?: string | null
  variants?: Record<string, string>
}

interface BedtimeConfig {
  enabled: boolean
  stories: {
    directories: string[]
    glob: string
  }
  viewer: {
    route: string
  }
  styles: {
    story: {
      container: string
      header: string
      content: string
    }
    variant: {
      container: string
      title: string
      content: string
    }
  }
}

export default defineNuxtModule<BedtimeConfig>({
  meta: {
    name: 'bedtime',
    configKey: 'bedtime',
    compatibility: {
      nuxt: '^3.0.0',
    },
  },
  defaults: {
    enabled: true,
    stories: {
      directories: ['./stories', './components'],
      glob: '**/*.story.vue',
    },
    viewer: {
      route: '/stories',
    },
    styles: {
      story: {
        container: '',
        header: '',
        content: '',
      },
      variant: {
        container: '',
        title: '',
        content: '',
      },
    },
  },
  async setup(options, nuxt) {
    if (!options.enabled) {
      return
    }

    const { stories: { glob: storyGlob, directories: storyDirectories }, viewer: { route: storyViewerRoute } } = options

    const resolver = createResolver(import.meta.url)
    const runtimeDir = resolver.resolve('./runtime')
    const logger = useLogger('bedtime')

    logger.info('Setting up bedtime module...')

    // Add type declarations
    addTypeTemplate({
      filename: 'module/bedtime.d.ts',
      getContents: () => `
// auto-generated by bedtime module
import type { Component } from 'vue'
import type { BedtimeStory, BedtimeStories } from '${resolve('src/types/module.ts')}'

export interface BedtimeConfig {
  stories: {
    directories: string[]
    glob: string
  }
  viewer: {
    enabled: boolean
    route: string
  }
}

export { BedtimeStory, BedtimeStories }

declare module '@nuxt/types' {
  interface NuxtOptions {
    bedtime?: Partial<BedtimeConfig>
  }
}

export {}
`,
    })

    // Add runtime directory to Nuxt
    nuxt.options.build.transpile.push(runtimeDir)

    // Add variables.css to Nuxt
    nuxt.options.css.push(resolve(runtimeDir, 'variables.css'))

    // Add composables directory
    nuxt.hook('imports:dirs', (dirs) => {
      dirs.push(resolve(runtimeDir, 'composables'))
    })

    const stories: Array<StoryComponent> = []

    // Create a stub stories.mjs file
    addTemplate({
      filename: 'stories.mjs',
      getContents: () => `
${stories.map(s => `import ${s.pascalName} from '${s.srcDir}'`).join('\n')}

export const stories = {
${stories.map(s => `  '${s.kebabName}': {
    kebabName: '${s.kebabName}',
    pascalName: '${s.pascalName}',
    shortPath: '${s.shortPath}',
    global: ${s.global},
    component: ${s.pascalName},
    template: ${JSON.stringify(s.template)},
    variants: ${JSON.stringify(s.variants)}
  }`).join(',\n')}
}
`,
    })

    // Add runtime components
    logger.debug('Adding runtime components directory:', resolve(runtimeDir, 'components'))
    await addComponentsDir({
      path: resolve(runtimeDir, 'components'),
      pathPrefix: false,
      prefix: '',
      global: true,
    })

    // Get all layers including the app itself
    const layerStoryDirs = [
      // Base layer (main app)
      {
        cwd: nuxt.options.srcDir,
        directories: storyDirectories,
      },
      // Additional layers
      ...nuxt.options._layers.map(layer => ({
        cwd: layer.cwd,
        directories: storyDirectories,
      })),
    ]

    // Add story components from all layers
    for (const { cwd, directories } of layerStoryDirs) {
      for (const dir of directories) {
        // Check if the directory exists
        const dirPath = resolve(cwd, dir)
        if (existsSync(dirPath)) {
          await addComponentsDir({
            path: dirPath,
            pattern: storyGlob,
            pathPrefix: false,
            prefix: '',
            global: true,
          })
        }
      }
    }

    nuxt.hook('components:extend', async (components) => {
      const storyComponents = components.filter(c =>
        c.pascalName.endsWith('Story') && c.pascalName !== 'Story',
      )

      const newStories = await Promise.all(storyComponents.map(async (component) => {
        const filePath = resolve(nuxt.options.srcDir, component.shortPath)
        const code = readFileSync(filePath, 'utf-8')
        const { descriptor } = parse(code)

        let template = null
        const variants: Record<string, string> = {}

        if (descriptor.template) {
          const { template: extractedTemplate, variants: extractedVariants }
            = extractStoryContent(descriptor.template.content, filePath, component.pascalName)
          template = extractedTemplate
          Object.assign(variants, extractedVariants)
        }

        return {
          kebabName: component.kebabName,
          pascalName: component.pascalName,
          shortPath: component.shortPath,
          global: component.global,
          srcDir: resolve(nuxt.options.srcDir, component.shortPath),
          template,
          variants,
        }
      }))

      // Only update if the stories have changed
      if (JSON.stringify(stories) !== JSON.stringify(newStories)) {
        logger.info(`Found ${storyComponents.length} story components`)
        stories.length = 0 // Clear the array
        stories.push(...newStories)
        await updateTemplates({
          filter: template => template.filename === 'stories.mjs',
        })
      }
    })

    // Add runtime routes
    nuxt.hook('pages:extend', (pages) => {
      if (!pages.some(page => page.name === 'stories-index')) {
        pages.push({
          name: 'stories-index',
          path: storyViewerRoute,
          file: resolver.resolve('./runtime/pages/stories-index.vue'),
        })
      }

      if (!pages.some(page => page.name === 'stories-slug')) {
        pages.push({
          name: 'stories-slug',
          path: `${storyViewerRoute}/:slug`,
          file: resolver.resolve('./runtime/pages/story-view.vue'),
        })
      }
    })

    // Add runtime config
    nuxt.options.runtimeConfig.public.bedtime = defu(
      nuxt.options.runtimeConfig.public.bedtime,
      { styles: options.styles },
    )

    logger.success('Bedtime module setup complete')
  },
})
